#!/bin/bash
set -e

# Miro MCP deployment script
# Deploys as internal service (not exposed via Traefik)
#
# Usage:
#   ./scripts/deploy.sh <env>
#
# Examples:
#   ./scripts/deploy.sh dev
#   ./scripts/deploy.sh production

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# ============================================
# Environment Selection
# ============================================

ENV="${1:-}"
if [ -z "$ENV" ]; then
    echo "Usage: $0 <environment>"
    echo ""
    echo "Available environments:"
    for conf in "$PROJECT_ROOT/config/env."*.conf; do
        if [ -f "$conf" ]; then
            env_name=$(basename "$conf" | sed 's/env\.\(.*\)\.conf/\1/')
            echo "  - $env_name"
        fi
    done
    exit 1
fi

CONFIG_FILE="$PROJECT_ROOT/config/env.${ENV}.conf"
if [ ! -f "$CONFIG_FILE" ]; then
    echo "Error: Configuration file not found: $CONFIG_FILE"
    exit 1
fi

source "$CONFIG_FILE"

echo "Deploying miro-mcp to $ENV..."
echo "Server: ${SERVER_USER}@${SERVER_HOST}"
echo "Path: ${DEPLOY_PATH}"
echo ""

# ============================================
# Load Secrets
# ============================================

if [ ! -f "$PROJECT_ROOT/$ENV_FILE" ]; then
    echo "Error: $ENV_FILE not found"
    exit 1
fi

source "$PROJECT_ROOT/$ENV_FILE"

if [ -z "$MIRO_CLIENT_ID_B64" ]; then
    echo "Error: MIRO_CLIENT_ID_B64 must be set in $ENV_FILE"
    exit 1
fi

echo "MIRO_CLIENT_ID: configured (base64)"
echo ""

# ============================================
# Build Locally
# ============================================

echo "Building TypeScript..."
cd "$PROJECT_ROOT"
npm run build

# ============================================
# Create Package
# ============================================

echo ""
echo "Creating deployment package..."
tar czf "/tmp/${TARBALL_NAME}" \
    --exclude='node_modules' \
    --exclude='.git' \
    --exclude='.env' \
    --exclude='.env.dev' \
    --exclude='.env.production' \
    --exclude='config' \
    --exclude='scripts' \
    dist \
    package.json \
    package-lock.json \
    docker-compose.yml \
    Dockerfile

echo "  Package: $(du -h "/tmp/${TARBALL_NAME}" | cut -f1)"

# ============================================
# Upload & Deploy
# ============================================

echo ""
echo "Uploading to server..."
ssh ${SERVER_USER}@${SERVER_HOST} "mkdir -p ${DEPLOY_PATH}"
scp "/tmp/${TARBALL_NAME}" ${SERVER_USER}@${SERVER_HOST}:${DEPLOY_PATH}/

echo ""
echo "Deploying on server..."

ssh ${SERVER_USER}@${SERVER_HOST} bash << REMOTE_EOF
set -e
cd ${DEPLOY_PATH}

# Clean and extract
echo "  Cleaning old deployment..."
find . -mindepth 1 -maxdepth 1 ! -name 'data' ! -name '${TARBALL_NAME}' -exec rm -rf {} + 2>&1 || true

echo "  Extracting..."
tar xzf ${TARBALL_NAME}
rm ${TARBALL_NAME}

# Generate .env
echo "  Generating .env..."
cat > .env << ENV_EOF
# ${ENV} Environment - Generated by deploy.sh
NODE_ENV=production
PORT=3000
BASE_URI=${BASE_URI}
MIRO_CLIENT_ID_B64=${MIRO_CLIENT_ID_B64}
MIRO_CLIENT_SECRET_B64=${MIRO_CLIENT_SECRET_B64}
# Tokens are generated via /oauth/authorize and stored in /data/tokens.json
ENV_EOF

# Ensure ingress network exists
echo "  Checking ingress network..."
docker network create ingress 2>/dev/null || true

# Stop old containers
echo "  Stopping old containers..."
${DOCKER_COMPOSE} down 2>/dev/null || true

# Build and start
echo "  Building Docker image..."
${DOCKER_COMPOSE} build

echo "  Starting service..."
${DOCKER_COMPOSE} up -d

# Wait
sleep 5

echo ""
echo "Container status:"
${DOCKER_COMPOSE} ps
REMOTE_EOF

# ============================================
# Verification
# ============================================

echo ""
echo "Verifying deployment..."

if ssh ${SERVER_USER}@${SERVER_HOST} "docker ps | grep -q miro-mcp"; then
    echo "  Container running"
else
    echo "Error: miro-mcp container not running!"
    ssh ${SERVER_USER}@${SERVER_HOST} "cd ${DEPLOY_PATH} && ${DOCKER_COMPOSE} logs"
    exit 1
fi

echo ""
echo "============================================"
echo "DEPLOYMENT SUCCESSFUL"
echo "Environment: $ENV"
echo "============================================"
echo ""
echo "Miro MCP is running as internal service."
echo "Access via mcp-gateway at: http://miro-mcp:3000"
echo ""
echo "View logs:"
echo "  ssh ${SERVER_USER}@${SERVER_HOST} 'cd ${DEPLOY_PATH} && ${DOCKER_COMPOSE} logs -f'"
